import { describe, expect, it } from "vitest";
import { parseFrontmatter } from "./document.ts";

/** A post written by hand: a comment, quoting, flow style, deliberate order. */
const POST = [
  "# generated by the import script",
  'title: "Hello, world"',
  "publishedAt: 2026-01-15",
  "draft: false",
  "tags: [astro, cms]",
  "legacyId: 4821",
  "",
].join("\n");

describe("parseFrontmatter", () => {
  it("changes one key and leaves everything else byte for byte", () => {
    const doc = parseFrontmatter(POST);

    doc?.set("draft", true);

    expect(doc?.toString()).toBe(POST.replace("draft: false", "draft: true"));
  });

  it("reads values with their YAML types", () => {
    const doc = parseFrontmatter(POST);

    expect(doc?.get("title")).toBe("Hello, world");
    expect(doc?.get("draft")).toBe(false);
    expect(doc?.get("publishedAt")).toBe("2026-01-15");
    expect(doc?.get("tags")).toEqual(["astro", "cms"]);
    expect(doc?.get("missing")).toBeUndefined();
  });

  it("lists keys in the order the file has them", () => {
    expect(parseFrontmatter(POST)?.keys()).toEqual([
      "title",
      "publishedAt",
      "draft",
      "tags",
      "legacyId",
    ]);
  });

  it("removes a key without disturbing the rest", () => {
    const doc = parseFrontmatter(POST);

    doc?.remove("legacyId");

    expect(doc?.toString()).toBe(POST.replace("legacyId: 4821\n", ""));
  });

  it("writes an array as a block sequence", () => {
    const doc = parseFrontmatter("title: Hi\n");

    doc?.set("tags", ["astro", "cms"]);

    expect(doc?.toString()).toBe("title: Hi\ntags:\n  - astro\n  - cms\n");
  });

  it("adds frontmatter to a post that had none", () => {
    const doc = parseFrontmatter(null);

    doc?.set("title", "First post");

    expect(doc?.toString()).toBe("title: First post\n");
  });

  it("leaves a post with no frontmatter empty rather than writing null", () => {
    expect(parseFrontmatter(null)?.toString()).toBe("");
    expect(parseFrontmatter("")?.toString()).toBe("");
  });

  it("returns undefined for YAML it cannot parse", () => {
    expect(parseFrontmatter("title: [unclosed")).toBeUndefined();
  });

  it("reads and writes one key as raw YAML text", () => {
    const doc = parseFrontmatter(POST);

    expect(doc?.getRaw("legacyId")).toBe("4821");
    expect(doc?.getRaw("tags")).toBe("- astro\n- cms");

    expect(doc?.setRaw("legacyId", "9999")).toBe(true);
    expect(doc?.get("legacyId")).toBe(9999);
  });

  it("refuses raw YAML it cannot parse and keeps the old value", () => {
    const doc = parseFrontmatter(POST);

    expect(doc?.setRaw("legacyId", "[unclosed")).toBe(false);
    expect(doc?.get("legacyId")).toBe(4821);
  });
});
