import { describe, expect, it } from "vitest";
import { parseFrontmatter } from "./document.ts";

/** A post written by hand: a comment, quoting, flow style, deliberate order. */
const POST = [
  "# generated by the import script",
  'title: "Hello, world"',
  "publishedAt: 2026-01-15",
  "draft: false",
  "tags: [astro, cms]",
  "legacyId: 4821",
  "",
].join("\n");

describe("parseFrontmatter", () => {
  it("changes one key and leaves everything else byte for byte", () => {
    const doc = parseFrontmatter(POST);

    doc?.set("draft", true);

    expect(doc?.toString()).toBe(POST.replace("draft: false", "draft: true"));
  });

  it("reads values with their YAML types", () => {
    const doc = parseFrontmatter(POST);

    expect(doc?.get("title")).toBe("Hello, world");
    expect(doc?.get("draft")).toBe(false);
    expect(doc?.get("publishedAt")).toBe("2026-01-15");
    expect(doc?.get("tags")).toEqual(["astro", "cms"]);
    expect(doc?.get("missing")).toBeUndefined();
  });

  it("lists keys in the order the file has them", () => {
    expect(parseFrontmatter(POST)?.keys()).toEqual([
      "title",
      "publishedAt",
      "draft",
      "tags",
      "legacyId",
    ]);
  });

  it("removes a key without disturbing the rest", () => {
    const doc = parseFrontmatter(POST);

    doc?.remove("legacyId");

    expect(doc?.toString()).toBe(POST.replace("legacyId: 4821\n", ""));
  });

  it("writes an array as a block sequence", () => {
    const doc = parseFrontmatter("title: Hi\n");

    doc?.set("tags", ["astro", "cms"]);

    expect(doc?.toString()).toBe("title: Hi\ntags:\n  - astro\n  - cms\n");
  });

  it("adds frontmatter to a post that had none", () => {
    const doc = parseFrontmatter(null);

    doc?.set("title", "First post");

    expect(doc?.toString()).toBe("title: First post\n");
  });

  it("leaves a post with no frontmatter empty rather than writing null", () => {
    expect(parseFrontmatter(null)?.toString()).toBe("");
    expect(parseFrontmatter("")?.toString()).toBe("");
  });

  it("returns undefined for YAML it cannot parse", () => {
    expect(parseFrontmatter("title: [unclosed")).toBeUndefined();
  });

  it("returns undefined for an alias bomb that parses cleanly but blows up on materialisation", () => {
    // Zero parse errors, but yaml's own resource-exhaustion guard throws
    // from `toJSON()` — which `parseFrontmatter` must trigger itself so the
    // throw happens here, not later inside a render with no error boundary.
    const bomb = [
      "a: &a [x,x]",
      "b0: &b0 [*a,*a]",
      "b1: &b1 [*b0,*b0]",
      "b2: &b2 [*b1,*b1]",
      "b3: &b3 [*b2,*b2]",
      "b4: &b4 [*b3,*b3]",
      "b5: &b5 [*b4,*b4]",
    ].join("\n");

    expect(parseFrontmatter(bomb)).toBeUndefined();
  });

  it("returns undefined for a self-referencing anchor that toJSON() accepts but JSON.stringify() cannot", () => {
    // toJSON() succeeds and returns a circular JS object; toControlValue
    // calls JSON.stringify on object values, so that must be proven too.
    const selfAnchor = "a: &a\n  self: *a";

    expect(parseFrontmatter(selfAnchor)).toBeUndefined();
  });

  it("reads and writes one key as raw YAML text", () => {
    const doc = parseFrontmatter(POST);

    expect(doc?.getRaw("legacyId")).toBe("4821");
    expect(doc?.getRaw("tags")).toBe("- astro\n- cms");

    expect(doc?.setRaw("legacyId", "9999")).toBe(true);
    expect(doc?.get("legacyId")).toBe(9999);
  });

  it("refuses raw YAML it cannot parse and keeps the old value", () => {
    const doc = parseFrontmatter(POST);

    expect(doc?.setRaw("legacyId", "[unclosed")).toBe(false);
    expect(doc?.get("legacyId")).toBe(4821);
  });

  it("reads an absent key as empty rather than throwing", () => {
    expect(parseFrontmatter(POST)?.getRaw("heroImage")).toBe("");
  });

  it("leaves a long line alone when another key changes", () => {
    const long = [
      "title: Hi",
      `description: ${"word ".repeat(30).trim()}`,
      "draft: false",
      "",
    ].join("\n");
    const doc = parseFrontmatter(long);

    doc?.set("draft", true);

    expect(doc?.toString()).toBe(long.replace("draft: false", "draft: true"));
  });
});
